swagger: '2.0'
info:
  description: This is the documentation for the api of OBD Server
  version: 1.0.0
  title: OBD Server API
host: localhost:2000
basePath: /
consumes:
- application/json
produces:
- application/json
schemes:
- http
paths: